#!/usr/bin/env bash

###
### NOTICE !!! You MUST have the appropriate modules loaded in your kernel for CPU sensors and speaker
###

# Set some parameters - ALARMTEMP is in celcius, MAXWAIT is in seconds
ALARMTEMP=55.0
MAXWAIT=5

# Verify required package(s)
command -v figlet >/dev/null 2>&1 || { echo >&2 "I require figlet but it's not installed.  Aborting."; exit 1; }
command -v beep >/dev/null 2>&1 || { echo >&2 "I require beep but it's not installed.  Aborting."; exit 1; }

# Alarm function
alarm() {
figlet "ALERT! CPU Temperature!"
while :; do for x in {800..1000}; do 
	beep -p ${x} 1; 
	done;
	CPUTEMP=`sysctl -a | grep dev.cpu.0.temperature | cut -d " " -f2 | cut -d "C" -f1`
	if ! (( $(bc <<<"$CPUTEMP > ${ALARMTEMP}") )); then
                cputemp;
        fi;
	tput sc
        printf "${CPUTEMP} :: ${ALARMTEMP}"
        tput rc
done
}

# CPU Temperature function
cputemp() {
while :; do
tput clear
CPUTEMP=`sysctl -a | grep dev.cpu.0.temperature | cut -d " " -f2 | cut -d "C" -f1`
if (( $(bc <<<"$CPUTEMP > ${ALARMTEMP}") )); then
	alarm
fi

figlet "${CPUTEMP} != ${ALARMTEMP}"
sleep $((RANDOM % MAXWAIT))
done
}

# Main
tput civis
cputemp
exit 0
